name: CI
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  all-cli-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "20.00"
      - run: mv .env.example .env
      - run: yarn install
      - run: yarn build
      - run: yarn test:jest
      - run: yarn lint
      - run: yarn check-format
      - run: yarn check-types
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "20.00"
      - run: mv .env.example .env
      - uses: cypress-io/github-action@v5
        with:
          build: yarn build
          start: yarn serve



  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel running workflows
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set node version
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Set pnpm version
        uses: pnpm/action-setup@v2
        with:
          run_install: false
          version: 7
      - name: Cache node_modules
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: node-modules-cache-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: pnpm install
      - name: Run tests
        run: pnpm test